# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 12:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='ad_cutomers')),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('date_adder', models.DateField(auto_now_add=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('time_wait', models.CharField(blank=True, max_length=200, null=True)),
                ('views', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('ad_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ads',
            },
        ),
        migrations.CreateModel(
            name='Analy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_cal', models.CharField(max_length=20)),
                ('views_cal', models.CharField(max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adengine.Ads')),
            ],
            options={
                'verbose_name': 'Analy',
            },
        ),
    ]
