# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adengine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analy',
            name='click_cal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='analy',
            name='views_cal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
