# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adengine', '0002_auto_20171005_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_cal', models.CharField(blank=True, max_length=20, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adengine.Ads')),
            ],
            options={
                'verbose_name': 'Clicks',
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_cal', models.CharField(blank=True, max_length=20, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adengine.Ads')),
            ],
            options={
                'verbose_name': 'Views',
            },
        ),
        migrations.RemoveField(
            model_name='analy',
            name='ads',
        ),
        migrations.DeleteModel(
            name='Analy',
        ),
    ]
