# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-06 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adengine', '0004_auto_20171006_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='date_added',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='view',
            name='date_added',
            field=models.DateTimeField(null=True),
        ),
    ]
