# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-06 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adengine', '0005_auto_20171006_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='view',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
