# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-06 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adengine', '0006_auto_20171006_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_ad_credit', models.BooleanField(default=False)),
                ('ad_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
