# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-12 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adengine', '0007_adsbuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='expired',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=40),
        ),
    ]
