# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-17 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adengine', '0009_ads_ad_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
