# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-18 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adengine', '0014_auto_20171017_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsbuy',
            name='ad_type',
            field=models.CharField(choices=[('Banner', 'Banner'), ('Products', 'Products')], default='Banner', max_length=200),
        ),
    ]
