# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-23 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylist',
            name='res_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
