# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-23 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_querylist_res_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylist',
            name='qury_bool',
            field=models.BooleanField(default=True),
        ),
    ]
