# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 21:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('female', 'female')], default='None', max_length=200)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('twitter_username', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('facebook_username', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('snapchat_username', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('bio', models.TextField(blank=True, default='', null=True)),
                ('page_views', models.IntegerField(default=0)),
                ('counter', models.IntegerField(default=0)),
                ('message_counter', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
