# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription',
            field=models.TextField(default='phones'),
            preserve_default=False,
        ),
    ]
