# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='l', max_length=800),
            preserve_default=False,
        ),
    ]
