# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agree_to_terms',
            field=models.BooleanField(default=True),
        ),
    ]
