# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('source_url', models.CharField(max_length=300)),
                ('shop', models.CharField(max_length=300)),
            ],
        ),
    ]
