# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='number_of_clicks',
            field=models.IntegerField(default=0),
        ),
    ]
