# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0002_products_number_of_clicks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_clicks', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='number_of_clicks',
        ),
        migrations.AddField(
            model_name='analytics',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='findit.Products'),
        ),
    ]
