# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0007_auto_20170604_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='images',
            new_name='image',
        ),
    ]
