# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0009_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feelings',
            field=models.IntegerField(blank=True, choices=[(100, 'Extremely satisfied'), (70, 'Moderately satisfied'), (40, 'Slightly satisfied'), (10, 'Neutral'), (5, 'Slightly dissatisfied'), (2, 'Moderately dissatisfied'), (1, 'Exteremely dissatisfied')], null=True),
        ),
    ]
