# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0011_auto_20170609_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='laptopAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_clicks', models.IntegerField(default=0)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('source_url', models.CharField(max_length=300)),
                ('shop', models.CharField(max_length=300)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='laptopanalytics',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='findit.Laptops'),
        ),
    ]
