# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 12:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('findit', '0013_feedback_createdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptops',
            name='user_sub',
            field=models.ManyToManyField(related_name='l_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='products',
            name='user_sub',
            field=models.ManyToManyField(related_name='ps_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
