# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0014_auto_20170616_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
