# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0015_products_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='real_price',
            field=models.IntegerField(default=0),
        ),
    ]
