# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0016_products_real_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sub_genre',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
