# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0017_products_sub_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='user_sub',
        ),
    ]
