# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 08:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('findit', '0018_remove_products_user_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='subcriptions',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
