# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0019_products_subcriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='old_price',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='products',
            name='old_price_digit',
            field=models.IntegerField(default=0),
        ),
    ]
