# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0020_auto_20170728_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptopanalytics',
            name='product',
        ),
        migrations.RemoveField(
            model_name='laptops',
            name='user_sub',
        ),
        migrations.DeleteModel(
            name='laptopAnalytics',
        ),
        migrations.DeleteModel(
            name='Laptops',
        ),
    ]
