# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0021_auto_20170728_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='url_locator',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
